version: "3.8"

services:
  postgres:
    image: postgis/postgis:latest
    restart: always
    container_name: naraDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: nara
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
